# Task 4.8

### Importing libraries

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import os

### Defining path variable

In [2]:
# defining the path variable
path = r'C:\Users\khand\Desktop\Careerfoundry\Data Immersion\Achievement - 4\04-2022 Instacart Basket Analysis'

### Importing dataframe

In [3]:
# importing dataframe
df_orders_products_merged = pd.read_pickle(os.path.join(path, '2. Data', 'Prepared Data', 'orders_products_merged_flagged.pkl'))

### Checking th imported dataframe

In [4]:
# checking the column names, data types and number of columns and rows
df_orders_products_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 19 columns):
 #   Column                     Dtype
---  ------                     -----
 0   order_id                   object
 1   user_id                    object
 2   order_number               int64
 3   order_day_of_week          object
 4   order_time_24h_format      object
 5   days_since_prior_order     float64
 6   product_id                 object
 7   add_to_cart_order          int64
 8   reordered                  int64
 9   merge_flag_1               category
 10  product_name               object
 11  aisle_id                   object
 12  department_id              object
 13  prices                     float64
 14  _merge                     category
 15  price_range                object
 16  busiest_day                object
 17  busiest_days               object
 18  busiest_period_of_the_day  object
dtypes: category(2), float64(2), int64(3), object(12)
memory usage: 4.4+ GB

In [5]:
# checking for null values 
df_orders_products_merged.isnull().sum()

order_id                           0
user_id                            0
order_number                       0
order_day_of_week                  0
order_time_24h_format              0
days_since_prior_order       2076096
product_id                         0
add_to_cart_order                  0
reordered                          0
merge_flag_1                       0
product_name                       0
aisle_id                           0
department_id                      0
prices                             0
_merge                             0
price_range                        0
busiest_day                        0
busiest_days                       0
busiest_period_of_the_day          0
dtype: int64

### Grouping by "department_id", aggregating mean of "order_number"

In [6]:
# grouping by "department_id", aggregating mean of "order_number"
df_orders_products_merged.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
2     17.277920
20    16.473447
21    22.902379
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
Name: order_number, dtype: float64

### Subsetting the first 1 million rows

In [7]:
# subsetting the first 1 million rows
df_subset = df_orders_products_merged[:1000000]

### Grouping by "department_id" aggregaring mean of "order_number" on the subset dataframe

In [8]:
# grouping by "department_id" aggregating mean of "order_number"
df_subset.groupby('department_id')['order_number'].mean()

department_id
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
4     18.825780
7     17.472355
Name: order_number, dtype: float64

#### Comparison of results: the average order number is different for every department when compared between the original and subset dataframes.

## Creating the loyalty flag

### Finding maximum "order_number" for each "user_id" with "transform()" function

In [9]:
# finding maximum "order_number" for each "user_id" with "transform()" function
df_orders_products_merged['max_orders'] = df_orders_products_merged.groupby('user_id')['order_number'].transform(np.max)

### Checking the updated dataframe after executing the "transform()" function

In [10]:
# checking the updated dataframe
df_orders_products_merged.head(50)

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,9
18,1573906,21,10,3,10,6.0,196,2,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,20
21,2580647,43,6,4,16,4.0,196,9,0,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
37,3205960,67,1,3,11,NaN,196,1,0,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
38,970922,67,2,1,15,5.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
41,2474111,67,5,3,14,8.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
44,2389031,67,9,2,14,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,196,1,1,both,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24

In [11]:
# checking the frequecy distribution of the "max_orders" column
df_orders_products_merged['max_orders'].value_counts(dropna = False)

99    1171333
8      811843
6      811396
9      810213
7      803979
       ...
97      44949
98      44587
96      40453
2           6
1           5
Name: max_orders, Length: 99, dtype: int64

In [12]:
# checking the "max_orders" column for null values
df_orders_products_merged['max_orders'].isnull().sum()

0

### Creating a loyalty flag based on the defined parameters

In [13]:
# condition 1: order number greater than 40
df_orders_products_merged.loc[df_orders_products_merged['max_orders'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [14]:
# condition 2: order number greater than 10 and less than or equal to 40
df_orders_products_merged.loc[(df_orders_products_merged['max_orders'] > 10) & (df_orders_products_merged['max_orders'] <= 40), 'loyalty_flag'] = 'Regular customer'

In [15]:
# condition 3: order number less than or equal to 10
df_orders_products_merged.loc[df_orders_products_merged['max_orders'] <= 10, 'loyalty_flag'] = 'New customer'

### Checking the loyalty flag

In [16]:
# checkign the 'loyalty_flag'
df_orders_products_merged['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

## Descriptive analysis using agg() function while grouping by "loyalty_flag"

In [17]:
# descriptive analysis using agg() function while grouping by "loyalty_flag"
df_orders_products_merged.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max', 'median']})

                     prices
                       mean  min      max median
loyalty_flag
Loyal customer    10.386336  1.0  99999.0    7.4
New customer      13.294670  1.0  99999.0    7.4
Regular customer  12.495717  1.0  99999.0    7.4

#### Comparison: The average prices of the products purchased by the loyal customers is lesser than the average prices of products purchased by other categories of customers. However, the minimum, maximum and median values are same for all categories

## Creating a spending flag

### Finding aggregate mean of "prices" while grouping by "user_id"

In [18]:
# creating a new column with aggregate mean of "prices" while grouping by "user_id"
df_orders_products_merged['avg_price'] = df_orders_products_merged.groupby('user_id')['prices'].transform(np.mean)

### Checking the updated dataframe

In [19]:
# checking the head of the updated dataframe
df_orders_products_merged.head(50)

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,...,department_id,prices,_merge,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders,loyalty_flag,avg_price
0,2539329,1,1,2,8,NaN,196,1,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
5,3367565,1,6,2,7,19.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
6,550135,1,7,1,9,20.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
7,3108588,1,8,1,14,14.0,196,2,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
8,2295261,1,9,1,16,0.0,196,4,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
9,2550362,1,10,4,8,30.0,196,1,1,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
10,2968173,15,15,1,9,7.0,196,2,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
11,1870022,15,17,2,16,8.0,196,6,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556
12,1911383,15,18,2,11,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556
13,2715276,15,21,1,9,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
14,487368,15,22,1,10,14.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
15,2293453,19,2,5,14,6.0,196,3,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059
16,1973799,19,5,6,12,8.0,196,15,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059
17,532817,19,7,4,17,6.0,196,1,1,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059
18,1573906,21,10,3,10,6.0,196,2,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683
19,1593000,31,10,3,8,7.0,196,17,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793
20,2231262,31,17,3,11,8.0,196,14,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793
21,2580647,43,6,4,16,4.0,196,9,0,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
22,2187180,43,9,4,12,3.0,196,1,1,both,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
23,2497897,52,1,1,9,NaN,196,4,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
24,1318871,52,2,1,10,7.0,196,5,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
25,1261384,52,3,1,10,7.0,196,3,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
26,580568,52,5,2,10,8.0,196,6,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
27,2428073,52,7,2,7,8.0,196,5,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27,Regular customer,6.356287
28,342306,52,9,1,11,7.0,196,5,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
29,1520353,52,10,2,10,8.0,196,4,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
30,2542086,52,11,2,9,7.0,196,3,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
31,944694,52,12,1,16,6.0,196,7,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
32,1268191,52,15,2,11,8.0,196,3,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
33,1122089,52,17,2,10,6.0,196,4,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
34,1498922,52,18,2,10,14.0,196,6,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
35,180919,52,19,3,8,8.0,196,4,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287
36,2695875,52,21,5,10,30.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287
37,3205960,67,1,3,11,NaN,196,1,0,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
38,970922,67,2,1,15,5.0,196,2,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
39,596585,67,3,1,13,7.0,196,2,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
40,2037087,67,4,2,9,8.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790
41,2474111,67,5,3,14,8.0,196,2,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
42,1568481,67,6,3,12,7.0,196,2,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
43,2048527,67,8,2,11,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790
44,2389031,67,9,2,14,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790
45,2378562,67,10,1,10,6.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
46,1515698,67,11,1,11,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
47,1928050,67,12,2,12,8.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790
48,1949274,67,13,1,10,6.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
49,551869,67,14,1,9,7.0,196,1,1,both,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790

In [20]:
# checking the frequency distribution of the "avg_price" column
df_orders_products_merged['avg_price'].value_counts(dropna = False)

8.000000     10337
7.500000      9116
8.100000      8254
7.750000      7048
7.400000      7044
             ...
13.800000        3
10.266667        3
2.700000         3
5.600000         3
12.200000        3
Name: avg_price, Length: 128637, dtype: int64

In [21]:
# checking if there is any null valyue in the 'avg_price' column
df_orders_products_merged['avg_price'].isnull().sum()

0

### Creating a price flag based on the "avg_price" column

In [22]:
# condition 1: average price of products purchased less than 10
df_orders_products_merged.loc[df_orders_products_merged['avg_price'] < 10, 'price_flag'] = 'Low spender'

In [23]:
# condition 2: average price of products purchased higher than or equal to 10
df_orders_products_merged.loc[df_orders_products_merged['avg_price'] >= 10, 'price_flag'] = 'High spender'

### Checking the price flag

In [24]:
# checking the updated dataframe
df_orders_products_merged.head(50)

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,...,prices,_merge,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders,loyalty_flag,avg_price,price_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender
1,2398795,1,2,3,7,15.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender
2,473747,1,3,3,12,21.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender
3,2254736,1,4,4,7,29.0,196,1,1,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender
4,431534,1,5,4,15,28.0,196,1,1,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender
5,3367565,1,6,2,7,19.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender
6,550135,1,7,1,9,20.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
7,3108588,1,8,1,14,14.0,196,2,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
8,2295261,1,9,1,16,0.0,196,4,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender
9,2550362,1,10,4,8,30.0,196,1,1,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender
10,2968173,15,15,1,9,7.0,196,2,0,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
11,1870022,15,17,2,16,8.0,196,6,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender
12,1911383,15,18,2,11,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender
13,2715276,15,21,1,9,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
14,487368,15,22,1,10,14.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender
15,2293453,19,2,5,14,6.0,196,3,0,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender
16,1973799,19,5,6,12,8.0,196,15,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender
17,532817,19,7,4,17,6.0,196,1,1,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059,Low spender
18,1573906,21,10,3,10,6.0,196,2,0,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683,Low spender
19,1593000,31,10,3,8,7.0,196,17,0,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793,Low spender
20,2231262,31,17,3,11,8.0,196,14,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793,Low spender
21,2580647,43,6,4,16,4.0,196,9,0,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender
22,2187180,43,9,4,12,3.0,196,1,1,both,...,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender
23,2497897,52,1,1,9,NaN,196,4,0,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
24,1318871,52,2,1,10,7.0,196,5,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
25,1261384,52,3,1,10,7.0,196,3,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
26,580568,52,5,2,10,8.0,196,6,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
27,2428073,52,7,2,7,8.0,196,5,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27,Regular customer,6.356287,Low spender
28,342306,52,9,1,11,7.0,196,5,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
29,1520353,52,10,2,10,8.0,196,4,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
30,2542086,52,11,2,9,7.0,196,3,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
31,944694,52,12,1,16,6.0,196,7,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender
32,1268191,52,15,2,11,8.0,196,3,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
33,1122089,52,17,2,10,6.0,196,4,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
34,1498922,52,18,2,10,14.0,196,6,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
35,180919,52,19,3,8,8.0,196,4,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287,Low spender
36,2695875,52,21,5,10,30.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender
37,3205960,67,1,3,11,NaN,196,1,0,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender
38,970922,67,2,1,15,5.0,196,2,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
39,596585,67,3,1,13,7.0,196,2,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
40,2037087,67,4,2,9,8.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender
41,2474111,67,5,3,14,8.0,196,2,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender
42,1568481,67,6,3,12,7.0,196,2,1,both,...,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender
43,2048527,67,8,2,11,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender
44,2389031,67,9,2,14,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender
45,2378562,67,10,1,10,6.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
46,1515698,67,11,1,11,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
47,1928050,67,12,2,12,8.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender
48,1949274,67,13,1,10,6.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender
49,551869,67,14,1,9,7.0,196,1,1,both,...,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender

In [25]:
# checking the frequency distribution of the "price_flag" column
df_orders_products_merged['price_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: price_flag, dtype: int64

## Creating a frequency flag

### Finding the median of "days_since_prior_order" for every "user_id"

In [26]:
# creating a new column with median of "days_since_prior_order" for each "user_id" using the "transform()" function
df_orders_products_merged['median_of_days_since_prior_order'] = df_orders_products_merged.groupby('user_id')['days_since_prior_order'].transform(np.median)

### Checking the updated dataframe

In [27]:
# checking the head of the updated dataframe
df_orders_products_merged.head(50)

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,...,_merge,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders,loyalty_flag,avg_price,price_flag,median_of_days_since_prior_order
0,2539329,1,1,2,8,NaN,196,1,0,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,both,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,both,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,196,2,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,196,4,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,196,1,1,both,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,196,2,0,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,196,6,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,196,3,0,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,196,15,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,196,1,1,both,...,both,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,196,2,0,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,196,17,0,both,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,196,14,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,196,9,0,both,...,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,196,1,1,both,...,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,196,4,0,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,196,5,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,196,3,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,196,6,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,196,5,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,196,5,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,196,4,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,196,3,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,196,7,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,196,3,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,196,4,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,196,6,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,196,4,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,196,1,0,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,196,2,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,196,2,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,196,2,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,196,2,1,both,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,196,1,1,both,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0

In [28]:
# checking frequency distribution of the "median_of_days_since_prior_order" column
df_orders_products_merged['median_of_days_since_prior_order'].value_counts(dropna = False)

7.0     5682399
6.0     2983604
8.0     2713964
5.0     2486061
4.0     2314289
         ...
26.5       5514
29.5       5095
1.5        1684
0.5         235
NaN           5
Name: median_of_days_since_prior_order, Length: 62, dtype: int64

In [29]:
# checking for any null vallue in the "median_of_days_since_prior_order" column
df_orders_products_merged['median_of_days_since_prior_order'].isnull().sum()

5

In [30]:
# checking the records with "null" in median flag
df_orders_products_merged[df_orders_products_merged['median_of_days_since_prior_order'].isnull() == True]

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,...,_merge,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders,loyalty_flag,avg_price,price_flag,median_of_days_since_prior_order
13645692,895835,159838,1,0,17,NaN,10749,3,0,both,...,both,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN
17251990,895835,159838,1,0,17,NaN,33401,6,0,both,...,both,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN
17622767,895835,159838,1,0,17,NaN,23695,2,0,both,...,both,Low-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN
24138593,895835,159838,1,0,17,NaN,21334,5,0,both,...,both,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN
25880002,895835,159838,1,0,17,NaN,22198,1,0,both,...,both,Low-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN

### Creating a frequency flag based on the "median_of_days_since_prior_order" column

In [31]:
# condition 1: median higher than 20
df_orders_products_merged.loc[df_orders_products_merged['median_of_days_since_prior_order'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [32]:
# condition 2: median higher than 10 and lower than or equal to 20
df_orders_products_merged.loc[(df_orders_products_merged['median_of_days_since_prior_order'] > 10) & (df_orders_products_merged['median_of_days_since_prior_order'] <= 20), 'frequency_flag'] = 'Regular customer'

In [33]:
# condition 3: median lower than or equal to 10
df_orders_products_merged.loc[df_orders_products_merged['median_of_days_since_prior_order'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [36]:
# condition 4: median = null
df_orders_products_merged.loc[df_orders_products_merged['median_of_days_since_prior_order'].isnull() == True, 'frequency_flag'] = 'New customer'

### Checking the udated dataframe

In [37]:
# checking the head of the updated dataframe
df_orders_products_merged.head(50)

,order_id,user_id,order_number,order_day_of_week,order_time_24h_format,days_since_prior_order,product_id,add_to_cart_order,reordered,merge_flag_1,...,price_range,busiest_day,busiest_days,busiest_period_of_the_day,max_orders,loyalty_flag,avg_price,price_flag,median_of_days_since_prior_order,frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,both,...,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,both,...,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,both,...,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
5,3367565,1,6,2,7,19.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
6,550135,1,7,1,9,20.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
7,3108588,1,8,1,14,14.0,196,2,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
8,2295261,1,9,1,16,0.0,196,4,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
9,2550362,1,10,4,8,30.0,196,1,1,both,...,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
10,2968173,15,15,1,9,7.0,196,2,0,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
11,1870022,15,17,2,16,8.0,196,6,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
12,1911383,15,18,2,11,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
13,2715276,15,21,1,9,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
14,487368,15,22,1,10,14.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
15,2293453,19,2,5,14,6.0,196,3,0,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
16,1973799,19,5,6,12,8.0,196,15,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
17,532817,19,7,4,17,6.0,196,1,1,both,...,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059,Low spender,6.0,Frequent customer
18,1573906,21,10,3,10,6.0,196,2,0,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer
19,1593000,31,10,3,8,7.0,196,17,0,both,...,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
20,2231262,31,17,3,11,8.0,196,14,1,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer
21,2580647,43,6,4,16,4.0,196,9,0,both,...,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
22,2187180,43,9,4,12,3.0,196,1,1,both,...,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer
23,2497897,52,1,1,9,NaN,196,4,0,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
24,1318871,52,2,1,10,7.0,196,5,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
25,1261384,52,3,1,10,7.0,196,3,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
26,580568,52,5,2,10,8.0,196,6,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
27,2428073,52,7,2,7,8.0,196,5,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
28,342306,52,9,1,11,7.0,196,5,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
29,1520353,52,10,2,10,8.0,196,4,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
30,2542086,52,11,2,9,7.0,196,3,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
31,944694,52,12,1,16,6.0,196,7,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
32,1268191,52,15,2,11,8.0,196,3,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
33,1122089,52,17,2,10,6.0,196,4,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
34,1498922,52,18,2,10,14.0,196,6,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
35,180919,52,19,3,8,8.0,196,4,1,both,...,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
36,2695875,52,21,5,10,30.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer
37,3205960,67,1,3,11,NaN,196,1,0,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
38,970922,67,2,1,15,5.0,196,2,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
39,596585,67,3,1,13,7.0,196,2,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
40,2037087,67,4,2,9,8.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
41,2474111,67,5,3,14,8.0,196,2,1,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
42,1568481,67,6,3,12,7.0,196,2,1,both,...,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
43,2048527,67,8,2,11,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
44,2389031,67,9,2,14,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
45,2378562,67,10,1,10,6.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
46,1515698,67,11,1,11,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
47,1928050,67,12,2,12,8.0,196,1,1,both,...,Mid-range product,Regularly busy,Regularly busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
48,1949274,67,13,1,10,6.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer
49,551869,67,14,1,9,7.0,196,1,1,both,...,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer

In [38]:
# checking frequency distribution of the "frequency_flag" column
df_orders_products_merged['frequency_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
New customer                    5
Name: frequency_flag, dtype: int64

## Exporting the updated dataframe to pickle format

In [39]:
# exporting the updated dataframe in .pkl format
df_orders_products_merged.to_pickle(os.path.join(path, '2. Data', 'Prepared Data', 'orders_products_merged_flagged_v2.pkl'))